In [2]:
import pandas as pd

data = pd.read_csv('dataset.csv')

In [3]:
data['Which activity do you dedicate most of your screen time to?  '].value_counts()

Which activity do you dedicate most of your screen time to?  
Entertainment (gaming, streaming, social media, etc.)    112
Academic/Work-related                                     88
Name: count, dtype: int64

In [4]:
data.columns

Index(['Timestamp', 'Which age group do you belong to? ',
       '  What is your gender?  ', 'What is your level of education? ',
       'What is your primary occupation ?',
       'How many hours in a day, on average, do you spend in front of screens?',
       'Which device do you use most frequently?',
       'Which activity do you dedicate most of your screen time to?  ',
       'Which app category do you use the most during your screen time?',
       'During which part of the day do you spend most of your screen time?',
       'What kind of environment helps you stay productive during screen use?',
       'After spending a long time in front of screens to complete a certain task, how do you generally feel about your productivity?',
       'How long can you generally stay focused on a single screen-based task without distractions?',
       'How do you try to stay focused while working on a complex task (e.g, coding)?',
       'While working on a screen-based task, how do you handle 

In [5]:
pd.crosstab(data['What is your primary occupation ?'], data['How many hours in a day, on average, do you spend in front of screens?'])

How many hours in a day, on average, do you spend in front of screens?  2–4  \
What is your primary occupation ?                                             
Professional                                                              5   
Student                                                                  17   

How many hours in a day, on average, do you spend in front of screens?  4–6  \
What is your primary occupation ?                                             
Professional                                                             13   
Student                                                                  38   

How many hours in a day, on average, do you spend in front of screens?  6–8  \
What is your primary occupation ?                                             
Professional                                                             13   
Student                                                                  38   

How many hours in a day, on average, do you spend in front of screens?  8-10  \
What is your primary occupation ?                                              
Professional                                                              27   
Student                                                                   17   

How many hours in a day, on average, do you spend in front of screens?  Less than 2  \
What is your primary occupation ?                                                     
Professional                                                                      0   
Student                                                                           1   

How many hours in a day, on average, do you spend in front of screens?  More than 10  
What is your primary occupation ?                                                     
Professional                                                                      18  
Student                                                                           13

In [6]:
data['What is your level of education? '].value_counts()

What is your level of education? 
Undergraduate           106
Graduate                 47
High school or below     47
Name: count, dtype: int64

In [7]:
data['What is your primary occupation ?'].value_counts()

What is your primary occupation ?
Student         124
Professional     76
Name: count, dtype: int64

In [8]:
data['What is your primary occupation ?'].value_counts()

What is your primary occupation ?
Student         124
Professional     76
Name: count, dtype: int64

In [9]:
import scipy.stats as stats
import numpy as np

# Preprocessing gender and screen time data
#data['What is your gender?'] = data[' What is your gender? '].str.strip()
data['Hours on screens'] = data['How many hours in a day, on average, do you spend in front of screens?'].str.strip()

# Define criteria for "more than 8 hours"
def classify_screen_time(hours):
    if '8-10' in hours or 'More than 10' in hours:
        return 'More than 8 hours'
    else:
        return '8 hours or less'

data['Screen Time Category'] = data['Hours on screens']#.apply(classify_screen_time)

# Chi-Square test between age group and screen time
age_screen_time_table = pd.crosstab(data['Which age group do you belong to? '], data['Screen Time Category'])

# Perform Chi-Square Test
chi2, p_value, dof, expected = stats.chi2_contingency(age_screen_time_table)

# Print results
print("Chi-Square Statistic:", round(chi2, 3))
print("P-value:", round(p_value, 3))
print("Degrees of Freedom:", dof)
print("Expected Frequencies:\n", expected)

if p_value < 0.05:
    print("Reject the null hypothesis: There is a significant association between age group and screen time category.")
else:
    print("Fail to reject the null hypothesis: No significant association between age group and screen time category.")

# Proportions for additional insights
age_group_proportions = age_screen_time_table.div(age_screen_time_table.sum(axis=1), axis=0)
print("Proportional distribution of screen time across age groups:\n", age_group_proportions)


Chi-Square Statistic: 25.457
P-value: 0.184
Degrees of Freedom: 20
Expected Frequencies:
 [[1.386e+01 3.213e+01 3.213e+01 2.772e+01 6.300e-01 1.953e+01]
 [2.640e+00 6.120e+00 6.120e+00 5.280e+00 1.200e-01 3.720e+00]
 [1.100e+00 2.550e+00 2.550e+00 2.200e+00 5.000e-02 1.550e+00]
 [6.600e-01 1.530e+00 1.530e+00 1.320e+00 3.000e-02 9.300e-01]
 [3.740e+00 8.670e+00 8.670e+00 7.480e+00 1.700e-01 5.270e+00]]
Fail to reject the null hypothesis: No significant association between age group and screen time category.
Proportional distribution of screen time across age groups:
 Screen Time Category                     2–4       4–6       6–8      8-10  \
Which age group do you belong to?                                            
18–24                               0.119048  0.230159  0.269841  0.206349   
25–34                               0.041667  0.166667  0.291667  0.250000   
35–44                               0.100000  0.200000  0.300000  0.300000   
45 and above                        

In [10]:
import scipy.stats as stats
import numpy as np

# Preprocessing gender and screen time data

data['Hours on screens'] = data['How many hours in a day, on average, do you spend in front of screens?'].str.strip()
data['What is your occupation?'] = data['What is your primary occupation ?'].str.strip()

# Define criteria for "more than 8 hours"
def classify_screen_time(hours):
    if '8-10' in hours or 'More than 10' in hours:
        return 'More than 8 hours'
    else:
        return '8 hours or less'

data['Screen Time Category'] = data['Hours on screens']#.apply(classify_screen_time)

# Chi-Square test between occupation (students vs. professionals) and screen time
occupation_filtered = data[data['What is your occupation?'].isin(['Student', 'Professional'])]
occupation_screen_time_table = pd.crosstab(occupation_filtered['What is your occupation?'], occupation_filtered['Screen Time Category'])
print(occupation_screen_time_table)
# Perform Chi-Square Test
chi2, p_value, dof, expected = stats.chi2_contingency(occupation_screen_time_table)

# Print results
print("Chi-Square Statistic:", round(chi2, 3))
print("P-value:", p_value)
print("Degrees of Freedom:", dof)
print("Expected Frequencies:\n", expected)

if p_value < 0.05:
    print("Reject the null hypothesis: There is a significant association between occupation and screen time category.")
else:
    print("Fail to reject the null hypothesis: No significant association between occupation and screen time category.")

# Proportions for additional insights
occupation_proportions = occupation_screen_time_table.div(occupation_screen_time_table.sum(axis=1), axis=0)
print("Proportional distribution of screen time across occupations:\n", occupation_proportions)


Screen Time Category      2–4  4–6  6–8  8-10  Less than 2  More than 10
What is your occupation?                                                
Professional                5   13   13    27            0            18
Student                    17   38   38    17            1            13
Chi-Square Statistic: 25.058
P-value: 0.00013580056428516966
Degrees of Freedom: 5
Expected Frequencies:
 [[ 8.36 19.38 19.38 16.72  0.38 11.78]
 [13.64 31.62 31.62 27.28  0.62 19.22]]
Reject the null hypothesis: There is a significant association between occupation and screen time category.
Proportional distribution of screen time across occupations:
 Screen Time Category           2–4       4–6       6–8      8-10  Less than 2  \
What is your occupation?                                                        
Professional              0.065789  0.171053  0.171053  0.355263     0.000000   
Student                   0.137097  0.306452  0.306452  0.137097     0.008065   

Screen Time Category      Mo

In [11]:
import scipy.stats as stats
import numpy as np

# Preprocessing gender and screen time data
#data['What is your gender?'] = data[' What is your gender?'].str.strip()
data['Hours on screens'] = data['How many hours in a day, on average, do you spend in front of screens?'].str.strip()
data['What is your occupation?'] = data['What is your occupation?'].str.strip()

# Define criteria for "more than 10 hours"
def classify_screen_time(hours):
    if 'More than 10' in hours:
        return 'More than 10 hours'
    else:
        return '10 hours or less'

data['Screen Time Category'] = data['Hours on screens'].apply(classify_screen_time)

# Chi-Square test between occupation (students vs. professionals) and screen time
occupation_filtered = data[data['What is your occupation?'].isin(['Student', 'Professional'])]
occupation_screen_time_table = pd.crosstab(occupation_filtered['What is your occupation?'], occupation_filtered['Screen Time Category'])
print(occupation_screen_time_table)
# Perform Chi-Square Test
chi2, p_value, dof, expected = stats.chi2_contingency(occupation_screen_time_table)

# Print results
print("Chi-Square Statistic:", round(chi2, 3))
print("P-value:", round(p_value, 3))
print("Degrees of Freedom:", dof)
print("Expected Frequencies:\n", expected)

if p_value < 0.05:
    print("Reject the null hypothesis: There is a significant association between occupation and screen time category.")
else:
    print("Fail to reject the null hypothesis: No significant association between occupation and screen time category.")

# Proportions for additional insights
occupation_proportions = occupation_screen_time_table.div(occupation_screen_time_table.sum(axis=1), axis=0)
print("Proportional distribution of screen time across occupations:\n", occupation_proportions)

Screen Time Category      10 hours or less  More than 10 hours
What is your occupation?                                      
Professional                            58                  18
Student                                111                  13
Chi-Square Statistic: 5.301
P-value: 0.021
Degrees of Freedom: 1
Expected Frequencies:
 [[ 64.22  11.78]
 [104.78  19.22]]
Reject the null hypothesis: There is a significant association between occupation and screen time category.
Proportional distribution of screen time across occupations:
 Screen Time Category      10 hours or less  More than 10 hours
What is your occupation?                                      
Professional                      0.763158            0.236842
Student                           0.895161            0.104839


In [12]:
#import pandas as pd
import scipy.stats as stats

# Preprocessing data: Strip unnecessary spaces
data['Primary screen activity'] = data['Which activity do you dedicate most of your screen time to?  '].str.strip()
data['Age group'] = data['Which age group do you belong to? '].str.strip()

# Create contingency table
age_activity_table = pd.crosstab(data['Age group'], data['Primary screen activity'])
age_activity_table.to_csv('cont')
print(age_activity_table)
# Perform Chi-Square Test
chi2, p_value, dof, expected = stats.chi2_contingency(age_activity_table)

# Print results
print("Chi-Square Statistic:", round(chi2, 3))
print("P-value:", p_value)
print("Degrees of Freedom:", dof)
print("Expected Frequencies:\n", expected)

if p_value < 0.05:
    print("Reject the null hypothesis: The distribution of primary screen activities is dependent on age group.")
else:
    print("Fail to reject the null hypothesis: The distribution of primary screen activities is independent of age group.")


Primary screen activity  Academic/Work-related  \
Age group                                        
18–24                                       52   
25–34                                       18   
35–44                                        8   
45 and above                                 6   
Below 18                                     4   

Primary screen activity  Entertainment (gaming, streaming, social media, etc.)  
Age group                                                                       
18–24                                                                   74      
25–34                                                                    6      
35–44                                                                    2      
45 and above                                                             0      
Below 18                                                                30      
Chi-Square Statistic: 36.976
P-value: 1.8218589786094068e-07
Degrees of Freedom: 4

In [13]:
import scipy.stats as stats
import numpy as np
import pandas as pd

data['App Category'] = data['Which app category do you use the most during your screen time?'].str.strip()
data['Productivity Level'] = data['After spending a long time in front of screens to complete a certain task, how do you generally feel about your productivity?'].str.strip()


# Test association between app category and productivity level
app_productivity_table = pd.crosstab(data['App Category'], data['Productivity Level'])

# Perform Chi-Square Test
chi2, p_value, dof, expected = stats.chi2_contingency(app_productivity_table)

# Print results
print("Chi-Square Statistic:", round(chi2, 3))
print("P-value:", round(p_value, 3))
print("Degrees of Freedom:", dof)
print("Expected Frequencies:\n", expected)

if p_value < 0.05:
    print("Reject the null hypothesis: There is a significant association between app category and productivity level.")
else:
    print("Fail to reject the null hypothesis: No significant association between app category and productivity level.")

# Proportions for additional insights
app_productivity_proportions = app_productivity_table.div(app_productivity_table.sum(axis=1), axis=0)
#print("Proportional distribution of productivity levels across app categories:\n", app_productivity_proportions)


Chi-Square Statistic: 12.977
P-value: 0.113
Degrees of Freedom: 8
Expected Frequencies:
 [[ 2.2    4.28   1.52 ]
 [ 5.775 11.235  3.99 ]
 [13.2   25.68   9.12 ]
 [27.5   53.5   19.   ]
 [ 6.325 12.305  4.37 ]]
Fail to reject the null hypothesis: No significant association between app category and productivity level.


In [14]:
import scipy.stats as stats
import numpy as np
import pandas as pd

data['Task Type'] = data['Does your attention span vary based on the type of task?'].str.strip()
data['Attention Span'] = data['How long can you generally stay focused on a single screen-based task without distractions?'].str.strip()


# Test association between app category and productivity level
task_attention_table = pd.crosstab(data['Attention Span'], data['Task Type'])

# Perform Chi-Square Test
chi2, p_value, dof, expected = stats.chi2_contingency(task_attention_table)

# Print results
print("Chi-Square Statistic:", round(chi2, 3))
print("P-value:", round(p_value, 3))
print("Degrees of Freedom:", dof)
print("Expected Frequencies:\n", expected)

if p_value < 0.05:
    print("Reject the null hypothesis: There is a significant association between task type and productivity level.")
else:
    print("Fail to reject the null hypothesis: No significant association between task type and productivity level.")

Chi-Square Statistic: 10.114
P-value: 0.341
Degrees of Freedom: 9
Expected Frequencies:
 [[16.32  17.92  21.44   8.32 ]
 [13.515 14.84  17.755  6.89 ]
 [ 8.925  9.8   11.725  4.55 ]
 [12.24  13.44  16.08   6.24 ]]
Fail to reject the null hypothesis: No significant association between task type and productivity level.


In [15]:
import scipy.stats as stats
import numpy as np
import pandas as pd

data['Task Type'] = data['Does your attention span vary based on the type of task?'].str.strip()
data['Productivity Level'] = data['After spending a long time in front of screens to complete a certain task, how do you generally feel about your productivity?'].str.strip()


# Test association between app category and productivity level
task_productivity_table = pd.crosstab(data['Productivity Level'], data['Task Type'])

# Perform Chi-Square Test
chi2, p_value, dof, expected = stats.chi2_contingency(task_productivity_table)

# Print results
print("Chi-Square Statistic:", round(chi2, 3))
print("P-value:", p_value)
print("Degrees of Freedom:", dof)
print("Expected Frequencies:\n", expected)

if p_value < 0.05:
    print("Reject the null hypothesis: There is a significant association between task type and productivity level.")
else:
    print("Fail to reject the null hypothesis: No significant association between task type and productivity level.")

Chi-Square Statistic: 12.582
P-value: 0.05016647948543116
Degrees of Freedom: 6
Expected Frequencies:
 [[14.025 15.4   18.425  7.15 ]
 [27.285 29.96  35.845 13.91 ]
 [ 9.69  10.64  12.73   4.94 ]]
Fail to reject the null hypothesis: No significant association between task type and productivity level.


In [35]:
import scipy.stats as stats
import numpy as np
import pandas as pd

data['Device Type'] = data['Which device do you use most frequently?'].str.strip()
data['Productivity Level'] = data['After spending a long time in front of screens to complete a certain task, how do you generally feel about your productivity?'].str.strip()

print(data['Device Type'].value_counts())
# Test association between app category and productivity level
device_productivity_table = pd.crosstab(data['Productivity Level'], data['Device Type'])
print(device_productivity_table)
# Perform Chi-Square Test
chi2, p_value, dof, expected = stats.chi2_contingency(device_productivity_table)

# Print results
print("Chi-Square Statistic:", round(chi2, 3))
print("P-value:", round(p_value, 3))
print("Degrees of Freedom:", dof)
print("Expected Frequencies:\n", expected)

if p_value < 0.05:
    print("Reject the null hypothesis: There is a significant association between device type and productivity level.")
else:
    print("Fail to reject the null hypothesis: No significant association between device type and productivity level.")

Device Type
Smartphone    126
Laptop/PC      72
Television      1
Tablet          1
Name: count, dtype: int64
Device Type                                         Laptop/PC  Smartphone  \
Productivity Level                                                          
Extremely productive, i efficiently complete my...         26          28   
Moderately productive                                      40          66   
Unproductive, i might not have completed the ta...          6          32   

Device Type                                         Tablet  Television  
Productivity Level                                                      
Extremely productive, i efficiently complete my...       1           0  
Moderately productive                                    0           1  
Unproductive, i might not have completed the ta...       0           0  
Chi-Square Statistic: 13.835
P-value: 0.032
Degrees of Freedom: 6
Expected Frequencies:
 [[19.8   34.65   0.275  0.275]
 [38.52  67.41   0.

In [17]:
import scipy.stats as stats
import numpy as np
import pandas as pd

data['Device Type'] = data['Which device do you use most frequently?'].str.strip()
data['Attention Span'] = data['How long can you generally stay focused on a single screen-based task without distractions?'].str.strip()


# Test association between app category and productivity level
device_attention_table = pd.crosstab(data['Attention Span'], data['Device Type'])

# Perform Chi-Square Test
chi2, p_value, dof, expected = stats.chi2_contingency(device_attention_table)

# Print results
print("Chi-Square Statistic:", round(chi2, 3))
print("P-value:", round(p_value, 3))
print("Degrees of Freedom:", dof)
print("Expected Frequencies:\n", expected)

if p_value < 0.05:
    print("Reject the null hypothesis: There is a significant association between device type and productivity level.")
else:
    print("Fail to reject the null hypothesis: No significant association between device type and productivity level.")

Chi-Square Statistic: 21.303
P-value: 0.011
Degrees of Freedom: 9
Expected Frequencies:
 [[23.04  40.32   0.32   0.32 ]
 [19.08  33.39   0.265  0.265]
 [12.6   22.05   0.175  0.175]
 [17.28  30.24   0.24   0.24 ]]
Reject the null hypothesis: There is a significant association between device type and productivity level.


In [18]:
import scipy.stats as stats
import numpy as np
import pandas as pd

data['Usage Time'] = data['During which part of the day do you spend most of your screen time?'].str.strip()
data['Productivity Level'] = data['After spending a long time in front of screens to complete a certain task, how do you generally feel about your productivity?'].str.strip()


# Test association between app category and productivity level
usagetime_productivity_table = pd.crosstab(data['Productivity Level'], data['Usage Time'])

# Perform Chi-Square Test
chi2, p_value, dof, expected = stats.chi2_contingency(usagetime_productivity_table)

# Print results
print("Chi-Square Statistic:", round(chi2, 3))
print("P-value:", p_value)
print("Degrees of Freedom:", dof)
print("Expected Frequencies:\n", expected)

if p_value < 0.05:
    print("Reject the null hypothesis: There is a significant association between usage time and productivity level.")
else:
    print("Fail to reject the null hypothesis: No significant association between usage time and productivity level.")

Chi-Square Statistic: 24.099
P-value: 0.000500882029798363
Degrees of Freedom: 6
Expected Frequencies:
 [[13.75  26.125 11.825  3.3  ]
 [26.75  50.825 23.005  6.42 ]
 [ 9.5   18.05   8.17   2.28 ]]
Reject the null hypothesis: There is a significant association between usage time and productivity level.


In [19]:
import pandas as pd
from statsmodels.stats.proportion import proportions_ztest

occupation_column = "What is your primary occupation ?"
productivity_column = "After spending a long time in front of screens to complete a certain task, how do you generally feel about your productivity?"

# Define the success criterion for high productivity
productivity_success_criterion = "Extremely productive, i efficiently complete my tasks"

# Filter data for students and professionals
students = data[data[occupation_column] == "Student"]
professionals = data[data[occupation_column] == "Professional"]

# Count successes and total observations for both groups based on productivity levels
student_productivity_successes = (students[productivity_column] == productivity_success_criterion).sum()
print(student_productivity_successes)
student_productivity_total = students[productivity_column].notna().sum()
professional_productivity_successes = (professionals[productivity_column] == productivity_success_criterion).sum()
print(professional_productivity_successes)
professional_productivity_total = professionals[productivity_column].notna().sum()

# Perform the z-test for proportions
productivity_successes = [student_productivity_successes, professional_productivity_successes]
productivity_totals = [student_productivity_total, professional_productivity_total]
z_stat_productivity, p_value_productivity = proportions_ztest(productivity_successes, productivity_totals)

print(f"Z-Statistic: {z_stat_productivity}, P-Value: {p_value_productivity}")

24
31
Z-Statistic: -3.2952121683964153, P-Value: 0.0009834739571675973


In [20]:
from scipy.stats import spearmanr, kendalltau
from sklearn.preprocessing import LabelEncoder

# Define relevant columns
screentime_column = "How many hours in a day, on average, do you spend in front of screens?"
productivity_column = "After spending a long time in front of screens to complete a certain task, how do you generally feel about your productivity?"

# Encode categorical data into ranks
label_encoder = LabelEncoder()
screentime_ranks = label_encoder.fit_transform(data[screentime_column])
productivity_ranks = label_encoder.fit_transform(data[productivity_column])

# Calculate Spearman and Kendall rank correlations
spearman_corr, spearman_p = spearmanr(screentime_ranks, productivity_ranks)
kendall_corr, kendall_p = kendalltau(screentime_ranks, productivity_ranks)

print(f"Spearman Correlation: {spearman_corr}, P-Value: {spearman_p}")
print(f"Kendall Correlation: {kendall_corr}, P-Value: {kendall_p}")


Spearman Correlation: -0.02754405991626965, P-Value: 0.698635020745048
Kendall Correlation: -0.02348609416652709, P-Value: 0.698686102045028


In [21]:
# Preprocessing data
data['App Category'] = data['Do you use tools/apps to monitor or manage your screen time?'].str.strip()
data['Productivity Level'] = data['How many hours in a day, on average, do you spend in front of screens?'].str.strip()

# Convert to numerical ranks
data['App Category Rank'] = pd.factorize(data['App Category'])[0]
data['Productivity Level Rank'] = pd.factorize(data['Productivity Level'])[0]

# Grouping data
app_groups = [data['Productivity Level Rank'][data['App Category Rank'] == level] 
              for level in np.unique(data['App Category Rank'])]

# Kruskal-Wallis Test
h_stat, p_value = stats.kruskal(*app_groups)
print("H-Statistic:", h_stat, "| P-value:", p_value)


H-Statistic: 7.470571064945928 | P-value: 0.02386635547625707


In [22]:
# Preprocessing data
data['App Category'] = data['Which activity do you dedicate most of your screen time to?  '].str.strip()
data['Productivity Level'] = data['How many hours in a day, on average, do you spend in front of screens?'].str.strip()

# Convert to numerical ranks
data['App Category Rank'] = pd.factorize(data['App Category'])[0]
data['Productivity Level Rank'] = pd.factorize(data['Productivity Level'])[0]

# Grouping data
app_groups = [data['Productivity Level Rank'][data['App Category Rank'] == level] 
              for level in np.unique(data['App Category Rank'])]

# Kruskal-Wallis Test
h_stat, p_value = stats.kruskal(*app_groups)
print("H-Statistic:", h_stat, "| P-value:", p_value)


H-Statistic: 9.063849858990418 | P-value: 0.0026071247164283044


In [23]:
from scipy.stats import norm

def runs_test_non_numeric(data, positive_group):
    """
    Perform a runs test for randomness on non-numeric data.

    Parameters:
    data (list): Sequence of categorical data.
    positive_group (list): Values to be considered as "+" (e.g., ["High"]).

    Returns:
    z (float): Z-statistic for the runs test.
    p_value (float): Two-tailed p-value.
    """
    # Convert data to "+" and "-"
    signs = ['+' if x in positive_group else '-' for x in data]

    # Count the number of runs
    runs = 1  # Start with 1 for the first sign
    for i in range(1, len(signs)):
        if signs[i] != signs[i - 1]:
            runs += 1

    # Number of "+" and "-"
    n1 = signs.count('+')
    n2 = signs.count('-')

    # Check for valid input
    if n1 == 0 or n2 == 0:
        raise ValueError("Data must contain at least one '+' and one '-' for the test.")

    # Calculate expected runs and standard deviation
    expected_runs = (2 * n1 * n2) / (n1 + n2) + 1
    std_dev = ((2 * n1 * n2 * (2 * n1 * n2 - n1 - n2)) /
               ((n1 + n2) ** 2 * (n1 + n2 - 1))) ** 0.5

    # Calculate Z-statistic
    z = (runs - expected_runs) / std_dev

    # Calculate two-tailed p-value
    p_value = 2 * (1 - norm.cdf(abs(z)))

    return z, p_value

# Example data
activity = data['Which activity do you dedicate most of your screen time to?  ']
positive_group = ["Entertainment (gaming, streaming, social media, etc.)"]  # Define "High" as the "+" group

# Runs test
try:
    z, p_value = runs_test_non_numeric(activity, positive_group)
    print(f"Z-statistic: {z}")
    print(f"P-value: {p_value}")
    
    if p_value > 0.05:
        print("Fail to reject the null hypothesis: Data is random.")
    else:
        print("Reject the null hypothesis: Data is not random.")
except ValueError as e:
    print(e)


Z-statistic: -1.5191624360536633
P-value: 0.12872161400456728
Fail to reject the null hypothesis: Data is random.


In [24]:
data['Do you use tools/apps to monitor or manage your screen time?'].unique()

array(['Yes, but i did not find them of any help',
       'No, i do not use them', 'Yes, they are extremely helpful'],
      dtype=object)

In [25]:
pd.crosstab(data['Do you use tools/apps to monitor or manage your screen time?'], data['How many hours in a day, on average, do you spend in front of screens?'])

How many hours in a day, on average, do you spend in front of screens?  2–4  \
Do you use tools/apps to monitor or manage your...                            
No, i do not use them                                                    10   
Yes, but i did not find them of any help                                  5   
Yes, they are extremely helpful                                           7   

How many hours in a day, on average, do you spend in front of screens?  4–6  \
Do you use tools/apps to monitor or manage your...                            
No, i do not use them                                                    31   
Yes, but i did not find them of any help                                  7   
Yes, they are extremely helpful                                          13   

How many hours in a day, on average, do you spend in front of screens?  6–8  \
Do you use tools/apps to monitor or manage your...                            
No, i do not use them                                                    28   
Yes, but i did not find them of any help                                  8   
Yes, they are extremely helpful                                          15   

How many hours in a day, on average, do you spend in front of screens?  8-10  \
Do you use tools/apps to monitor or manage your...                             
No, i do not use them                                                     33   
Yes, but i did not find them of any help                                   4   
Yes, they are extremely helpful                                            7   

How many hours in a day, on average, do you spend in front of screens?  Less than 2  \
Do you use tools/apps to monitor or manage your...                                    
No, i do not use them                                                             1   
Yes, but i did not find them of any help                                          0   
Yes, they are extremely helpful                                                   0   

How many hours in a day, on average, do you spend in front of screens?  More than 10  
Do you use tools/apps to monitor or manage your...                                    
No, i do not use them                                                             20  
Yes, but i did not find them of any help                                           9  
Yes, they are extremely helpful                                                    2

In [26]:
import scipy.stats as stats
import numpy as np

# Preprocessing gender and screen time data
#data['What is your gender?'] = data[' What is your gender? '].str.strip()
data['Hours on screens'] = data['How many hours in a day, on average, do you spend in front of screens?'].str.strip()

# Define criteria for "more than 8 hours"
def classify_screen_time(hours):
    if '8-10' in hours or 'More than 10' in hours:
        return 'More than 8 hours'
    else:
        return '8 hours or less'

data['Screen Time Category'] = data['Hours on screens'].apply(classify_screen_time)

# Chi-Square test between age group and screen time
age_screen_time_table = pd.crosstab(data['Do you use tools/apps to monitor or manage your screen time?'], data['Screen Time Category'])
print(age_screen_time_table)
# Perform Chi-Square Test
chi2, p_value, dof, expected = stats.chi2_contingency(age_screen_time_table)

# Print results
print("Chi-Square Statistic:", round(chi2, 3))
print("P-value:", round(p_value, 3))
print("Degrees of Freedom:", dof)
print("Expected Frequencies:\n", expected)

if p_value < 0.05:
    print("Reject the null hypothesis: There is a significant association between age group and screen time category.")
else:
    print("Fail to reject the null hypothesis: No significant association between age group and screen time category.")

# Proportions for additional insights
age_group_proportions = age_screen_time_table.div(age_screen_time_table.sum(axis=1), axis=0)
print("Proportional distribution of screen time across age groups:\n", age_group_proportions)


Screen Time Category                                8 hours or less  \
Do you use tools/apps to monitor or manage your...                    
No, i do not use them                                            70   
Yes, but i did not find them of any help                         20   
Yes, they are extremely helpful                                  35   

Screen Time Category                                More than 8 hours  
Do you use tools/apps to monitor or manage your...                     
No, i do not use them                                              53  
Yes, but i did not find them of any help                           13  
Yes, they are extremely helpful                                     9  
Chi-Square Statistic: 7.145
P-value: 0.028
Degrees of Freedom: 2
Expected Frequencies:
 [[76.875 46.125]
 [20.625 12.375]
 [27.5   16.5  ]]
Reject the null hypothesis: There is a significant association between age group and screen time category.
Proportional distribution of screen t

In [27]:
tools = data.loc[:,'Do you use tools/apps to monitor or manage your screen time?']

tools

0      Yes, but i did not find them of any help
1                         No, i do not use them
2                         No, i do not use them
3                         No, i do not use them
4                         No, i do not use them
                         ...                   
195                       No, i do not use them
196    Yes, but i did not find them of any help
197    Yes, but i did not find them of any help
198                       No, i do not use them
199             Yes, they are extremely helpful
Name: Do you use tools/apps to monitor or manage your screen time?, Length: 200, dtype: object

In [28]:
#import pandas as pd
import scipy.stats as stats

#dat = data[data['What kind of environment helps you stay productive during screen use?']!='I can work in any environment']
# Preprocessing data: Strip unnecessary spaces
data['environ'] = data['What kind of environment helps you stay productive during screen use?'].str.strip()
data['att'] = data['How long can you generally stay focused on a single screen-based task without distractions?']
data['prod'] = data['After spending a long time in front of screens to complete a certain task, how do you generally feel about your productivity?'].str.strip()
data['notif'] = data['While working on a screen-based task, how do you handle frequent notifications which distract you?']

# Create contingency table
age_activity_table = pd.crosstab(data['notif'], data['att'])
age_activity_table.to_csv('cont')
print(age_activity_table)
# Perform Chi-Square Test
chi2, p_value, dof, expected = stats.chi2_contingency(age_activity_table)

# Print results
print("Chi-Square Statistic:", round(chi2, 3))
print("P-value:", p_value)
print("Degrees of Freedom:", dof)
print("Expected Frequencies:\n", expected)

if p_value < 0.05:
    print("Reject the null hypothesis: The distribution of primary screen activities is dependent on age group.")
else:
    print("Fail to reject the null hypothesis: The distribution of primary screen activities is independent of age group.")


att                                            10–30 minutes  30–60 minutes  \
notif                                                                         
Check them briefly and resume my work                     23             22   
Ignore them until my task is completed                    10             10   
Spend time interacting with the notifications              8              1   
Turn off notifications altogether                         23             20   

att                                            Less than 10 minutes  \
notif                                                                 
Check them briefly and resume my work                             9   
Ignore them until my task is completed                            7   
Spend time interacting with the notifications                     6   
Turn off notifications altogether                                13   

att                                            More than 1 hour  
notif                           

In [29]:
#import pandas as pd
import scipy.stats as stats

#dat = data[data['What kind of environment helps you stay productive during screen use?']!='I can work in any environment']
# Preprocessing data: Strip unnecessary spaces
data['environ'] = data['What kind of environment helps you stay productive during screen use?'].str.strip()
data['att'] = data['How long can you generally stay focused on a single screen-based task without distractions?']
data['prod'] = data['After spending a long time in front of screens to complete a certain task, how do you generally feel about your productivity?'].str.strip()
data['notif'] = data['While working on a screen-based task, how do you handle frequent notifications which distract you?']

# Create contingency table
age_activity_table = pd.crosstab(data['notif'], data['att'])
age_activity_table.to_csv('cont')
print(age_activity_table)
# Perform Chi-Square Test
chi2, p_value, dof, expected = stats.chi2_contingency(age_activity_table)

# Print results
print("Chi-Square Statistic:", round(chi2, 3))
print("P-value:", p_value)
print("Degrees of Freedom:", dof)
print("Expected Frequencies:\n", expected)

if p_value < 0.05:
    print("Reject the null hypothesis: The distribution of primary screen activities is dependent on age group.")
else:
    print("Fail to reject the null hypothesis: The distribution of primary screen activities is independent of age group.")


att                                            10–30 minutes  30–60 minutes  \
notif                                                                         
Check them briefly and resume my work                     23             22   
Ignore them until my task is completed                    10             10   
Spend time interacting with the notifications              8              1   
Turn off notifications altogether                         23             20   

att                                            Less than 10 minutes  \
notif                                                                 
Check them briefly and resume my work                             9   
Ignore them until my task is completed                            7   
Spend time interacting with the notifications                     6   
Turn off notifications altogether                                13   

att                                            More than 1 hour  
notif                           

In [30]:
data['How do you try to stay focused while working on a complex task (e.g, coding)?'].unique()

array(['Take regular breaks',
       'None, i prefer to work without any strategies',
       'Eliminate all distractions',
       'Use some productivity tool (e.g, timers, blockers)', nan],
      dtype=object)

In [31]:
#import pandas as pd
import scipy.stats as stats

#dat = data[data['What kind of environment helps you stay productive during screen use?']!='I can work in any environment']
# Preprocessing data: Strip unnecessary spaces
data['environ'] = data['What kind of environment helps you stay productive during screen use?'].str.strip()
data['att'] = data['How long can you generally stay focused on a single screen-based task without distractions?']
data['prod'] = data['After spending a long time in front of screens to complete a certain task, how do you generally feel about your productivity?'].str.strip()
data['notif'] = data['While working on a screen-based task, how do you handle frequent notifications which distract you?']
data['strat'] = data['How do you try to stay focused while working on a complex task (e.g, coding)?']
# Create contingency table
age_activity_table = pd.crosstab(data['notif'], data['att'])
age_activity_table.to_csv('cont')
print(age_activity_table)
# Perform Chi-Square Test
chi2, p_value, dof, expected = stats.chi2_contingency(age_activity_table)

# Print results
print("Chi-Square Statistic:", round(chi2, 3))
print("P-value:", p_value)
print("Degrees of Freedom:", dof)
print("Expected Frequencies:\n", expected)

if p_value < 0.05:
    print("Reject the null hypothesis: The distribution of primary screen activities is dependent on age group.")
else:
    print("Fail to reject the null hypothesis: The distribution of primary screen activities is independent of age group.")


att                                            10–30 minutes  30–60 minutes  \
notif                                                                         
Check them briefly and resume my work                     23             22   
Ignore them until my task is completed                    10             10   
Spend time interacting with the notifications              8              1   
Turn off notifications altogether                         23             20   

att                                            Less than 10 minutes  \
notif                                                                 
Check them briefly and resume my work                             9   
Ignore them until my task is completed                            7   
Spend time interacting with the notifications                     6   
Turn off notifications altogether                                13   

att                                            More than 1 hour  
notif                           

In [32]:
import scipy.stats as stats
import numpy as np

# Preprocessing gender and screen time data
#data['What is your gender?'] = data[' What is your gender? '].str.strip()
data['Hours on screens'] = data['How many hours in a day, on average, do you spend in front of screens?'].str.strip()

# Define criteria for "more than 8 hours"
def classify_screen_time(hours):
    if '8-10' in hours or 'More than 10' in hours:
        return 'More than 8 hours'
    else:
        return '8 hours or less'

data['Screen Time Category'] = data['Hours on screens'].apply(classify_screen_time)

# Chi-Square test between age group and screen time
age_screen_time_table = pd.crosstab(data['Screen Time Category'], data['How long can you generally stay focused on a single screen-based task without distractions?'])

# Perform Chi-Square Test
chi2, p_value, dof, expected = stats.chi2_contingency(age_screen_time_table)

# Print results
print("Chi-Square Statistic:", round(chi2, 3))
print("P-value:", round(p_value, 3))
print("Degrees of Freedom:", dof)
print("Expected Frequencies:\n", expected)

if p_value < 0.05:
    print("Reject the null hypothesis: There is a significant association between age group and screen time category.")
else:
    print("Fail to reject the null hypothesis: No significant association between age group and screen time category.")

# Proportions for additional insights
age_group_proportions = age_screen_time_table.div(age_screen_time_table.sum(axis=1), axis=0)
#print("Proportional distribution of screen time across age groups:\n", age_group_proportions)


Chi-Square Statistic: 2.492
P-value: 0.477
Degrees of Freedom: 3
Expected Frequencies:
 [[40.    33.125 21.875 30.   ]
 [24.    19.875 13.125 18.   ]]
Fail to reject the null hypothesis: No significant association between age group and screen time category.


In [33]:
data['After spending a long time in front of screens to complete a certain task, how do you generally feel about your productivity?'].unique()

array(['Moderately productive',
       'Extremely productive, i efficiently complete my tasks',
       'Unproductive, i might not have completed the task and got carried away'],
      dtype=object)

In [34]:
data.loc[data['

SyntaxError: unterminated string literal (detected at line 1) (2197748062.py, line 1)

In [65]:
import pandas as pd
from statsmodels.stats.proportion import proportions_ztest

# Sample data (replace this with your actual DataFrame)
# Columns: 'During which part of the day do you spend most of your screen time?' and 'After spending a long time in front of screens to complete a certain task, how do you generally feel about your productivity?'

# Step 1: Combine 'Morning' and 'Afternoon' into 'Day', and 'Evening' and 'Late night' into 'Night'
data['Time of Day'] = data['During which part of the day do you spend most of your screen time?'].replace(
    ['Morning (6 AM–12 PM)', 'Afternoon (12 PM–6 PM)'], 'Day')
data['Time of Day'] = data['Time of Day'].replace(
    ['Evening (6 PM–10 PM)', 'Late night (10 PM–6 AM)'], 'Night')

# Step 2: Proportion of high productivity
day_high_productivity = data[(data['Time of Day'] == 'Day') & 
                             (data['After spending a long time in front of screens to complete a certain task, how do you generally feel about your productivity?'] == 'Extremely productive, i efficiently complete my tasks')].shape[0] / \
                        data[data['Time of Day'] == 'Day'].shape[0]

night_high_productivity = data[(data['Time of Day'] == 'Night') & 
                              (data['After spending a long time in front of screens to complete a certain task, how do you generally feel about your productivity?'] == 'Extremely productive, i efficiently complete my tasks')].shape[0] / \
                         data[data['Time of Day'] == 'Night'].shape[0]

# Step 3: Perform the proportion Z-test
z_stat, p_value = proportions_ztest(
    [day_high_productivity * data[data['Time of Day'] == 'Day'].shape[0],
     night_high_productivity * data[data['Time of Day'] == 'Night'].shape[0]],
    [data[data['Time of Day'] == 'Day'].shape[0], data[data['Time of Day'] == 'Night'].shape[0]]
)

# Step 4: Interpret the results
alpha = 0.05  # Significance level
if p_value < alpha:
    print(f"Reject the null hypothesis: There is a significant difference in high productivity proportions between Day and Night (p = {p_value:.4f})")
else:
    print(f"Fail to reject the null hypothesis: No significant difference in high productivity proportions between Day and Night (p = {p_value:.4f})")


Reject the null hypothesis: There is a significant difference in high productivity proportions between Day and Night (p = 0.0022)
